### ISSUE TITLE
Wechat.php变量错误

### ISSUE THREAD

**Issue by Hanchengluo** [kuif/pay#2]
private function getEncrypt($str) {部分
 if (openssl_public_encrypt($str, $encrypted, $public_key, OPENSSL_PKCS1_OAEP_PADDING))
应为if (openssl_public_encrypt($str, $encrypted, $publicKey, OPENSSL_PKCS1_OAEP_PADDING)) {

**Comment by Hanchengluo** [comment]
https://docs.fengkui.net/pay/wechat/profitsharing.html#%E6%B7%BB%E5%8A%A0%E5%88%86%E8%B4%A6%E6%8E%A5%E6%94%B6%E6%96%B9  中$result = $pay->receiversAdd($$account, $type, $name);写多了$$

**Comment by kuif** [comment]
多谢提醒，两个问题已修改

**Comment by kuif** [comment]
111
