### ISSUE TITLE
php 8.2 兼容

### ISSUE THREAD

**Issue by codediy** [kuif/pay#3]
<img width="539" alt="81230f420717bf57b19bc517d95ed2a" src="https://github.com/kuif/pay/assets/20250924/75a3b145-1106-4f9a-b23a-2fd288510e41">
![image](https://github.com/kuif/pay/assets/20250924/e50edcb8-fde8-4f60-8aff-5fcea9caa157)

![image](https://github.com/kuif/pay/assets/20250924/49cef9ed-fd42-4859-b1a9-a0fdeb5bc782)

**Comment by codediy** [comment]
$url_parts = parse_url($url);
//        $url = ($url_parts['path'] . (!empty($url_parts['query']) ? "?${url_parts['query']}" : ""));

**Comment by codediy** [comment]
//        $url = ($url_parts['path'] . (!empty($url_parts['query']) ? "?${url_parts['query']}" : ""));
        $url = $url_parts['path'] . (!empty($url_parts['query']) ? '?'.$url_parts['query'] : "");

**Comment by kuif** [comment]
感谢反馈，已更新
